--뷰 이름은 자유
--1) 학생의 평점 4.5 만점으로 환산된 정보를 검색할 수 있는 뷰를 생성하세요.
CREATE OR REPLACE VIEW V_AVG
(STUDENT_NO, STUDENT_NAME, STUDENT_AVR)
AS (SELECT S.SNO, S.SNAME, S.AVR*1.125 AS SAVR FROM STUDENT S);

--2) 각 과목별 기말고사 평균 점수를 검색할 수 있는 뷰를 생성하세요.
CREATE OR REPLACE VIEW V_AVR_RESULT
(COURSE_NO, COURSE_NAME, SCORE_RESULT)
AS (SELECT C.CNO, C.CNAME, AVG(SC.RESULT) FROM STUDENT S JOIN SCORE SC ON S.SNO = SC.SNO
	JOIN COURSE C ON SC.CNO = C.CNO GROUP BY C.CNO, C.CNAME);

--3) 각 사원과 관리자(MGR)의 이름을 검색할 수 있는 뷰를 생성하세요.
CREATE OR REPLACE VIEW V_EMP_MGR
(EMP_NO, EMP_NAME, EMP_MGR, MGR_NAME)
AS (SELECT E.ENO,
       E.ENAME,
       E.MGR,
       EE.ENAME
	FROM EMP E
	LEFT JOIN EMP EE ON E.MGR = EE.ENO);

--4) 각 과목별 기말고사 평가 등급(A~F)까지와 해당 학생 정보를 검색할 수 있는 뷰를 생성하세요.
CREATE OR REPLACE VIEW V_STU_INFO
(SNO, SNAME, RESULT, GRADE)
AS (SELECT S.SNO, S.SNAME, C.CNAME, SCG.GRADE 
	FROM STUDENT S JOIN SCORE SC ON S.SNO = SC.SNO JOIN COURSE C ON SC.CNO = C.CNO
	JOIN SCGRADE SCG ON SC.RESULT BETWEEN SCG.LOSCORE AND SCG.HISCORE);

--5) 물리학과 교수의 과목을 수강하는 학생의 명단을 검색할 뷰를 생성하세요.
CREATE OR REPLACE VIEW V_PROF_COR
(SNAME, PNO, PNAME)
AS (SELECT S.SNAME, P.PNO, P.PNAME
	FROM STUDENT S JOIN SCORE SC ON S.SNO = SC.SNO JOIN COURSE C ON SC.CNO = C.CNO 
	JOIN PROFESSOR P ON C.PNO = P.PNO WHERE P.SECTION = '물리');







