--1) CNO이 PK인 COURSE_PK 테이블을 생성하세요.(1번 방식으로)
CREATE TABLE COURSE_PK3(
    CNO NUMBER PRIMARY KEY,
    CNAME VARCHAR2(20),
    ST_NUM NUMBER(1),
    PNO NUMBER
);

--2) PNO이 PK인 PROFESSOR_PK 테이블을 생성하세요.(2번 방식으로)
CREATE TABLE PROFESSOR_PK(
    PNO NUMBER,
    PNAME VARCHAR2(20),
    SECTION VARCHAR2(10),
    ORDERS VARCHAR2(10),
    HIREDATE DATE,
    CONSTRAINT PK_PF_PNO1 PRIMARY KEY(PNO)
);

--3) PF_TEMP 테이블에 PNO을 PK로 추가하세요.
ALTER TABLE PF_TEMP
    DROP PRIMARY KEY;
    
ALTER TABLE PF_TEMP
    ADD CONSTRAINT PK_PT_PNO PRIMARY KEY(PNO);

--4) COURSE_PROFESSOR 테이블에 CNO, PNO을 PK로 추가하세요.
ALTER TABLE COURSE_PROFESSOR
    DROP PRIMARY KEY;
    
ALTER TABLE COURSE_PROFESSOR
    ADD CONSTRAINT PK_CP_CPNO PRIMARY KEY(CNO, PNO);

--5) BOARD_NO(NUMBER)를 PK로 갖으면서 BOARD_TITLE(VARCHAR2(200)), BOARD_CONTENT(VARCHAR2(2000)), 
--   BOARD_WRITER(VARCHAR2(20)), BOARD_FRGT_DATE(DATE), BOARD_LMDF_DATE(DATE) 컬럼을 갖는 T_BOARD 테이블을 생성하세요.
DROP TABLE T_BOARD;

CREATE TABLE T_BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_TITLE VARCHAR2(200),
    BOARD_CONTENT VARCHAR2(2000),
    BOARD_WRITER VARCHAR2(20),
    BOARD_FRGT_DATE DATE,
    BOARD_LMDF_DATE DATE
);

--6) BOARD_NO(NUMBER), BOARD_FILE_NO(NUMBER)를 PK로 갖으면서 BOARD_FILE_NM(VARCHAR2(200)), BOARD_FILE_PATH(VARCHAR2(2000)),
--   ORIGIN_FILE_NM(VARCHAR2(200)) 컬럼을 갖는 T_BOARD_FILE 테이블을 생성하세요.
DROP TABLE T_BOARD_FILE;

CREATE TABLE T_BOARD_FILE(
    BOARD_NO NUMBER,
    BOARD_FILE_NO NUMBER,
    BOARD_FILE_NM VARCHAR2(200),
    BOARD_FILE_PATH VARCHAR2(2000),
    ORIGIN_FILE_NM VARCHAR2(200),
    CONSTRAINT PK_BF_BOARD_FILE_NO PRIMARY KEY(BOARD_NO, BOARD_FILE_NO)
);

--7) 다음 구조를 갖는 테이블을 생성하세요.
--   T_SNS                              T_SNS_DETAIL                        T_SNS_UPLOADED
--   SNS_NO(PK)    SNS_NM               SNS_NO(PK, FK)   SNS_BEN            SNS_NO(PK, FK)    SNS_UPL_NO(PK)
--     1            페북                   1               4000                   1                  1
--     2           인스타                  2               10000                  1                  2
--     3           트위터                  3               30000                  2                  1
--                                                                               2                  2
CREATE TABLE T_SNS1(
    SNS_NO NUMBER,
    SNS_NM VARCHAR2(20),
    CONSTRAINT PK_SNS_NO PRIMARY KEY(SNS_NO)
);

CREATE TABLE T_SNS_DETAIL1(
    SNS_NO NUMBER,
    SNS_BEN NUMBER(6),
    CONSTRAINT PK_SNS_DET_NO PRIMARY KEY(SNS_NO),
    CONSTRAINT FK_SNS_DET_NO FOREIGN KEY(SNS_NO)
        REFERENCES T_SNS1(SNS_NO)
);

CREATE TABLE T_SNS_UPLOADED1(
    SNS_NO NUMBER,
    SNS_UP_NO NUMBER,
    CONSTRAINT PK_SNS_UP_NO PRIMARY KEY(SNS_NO, SNS_UP_NO),
    CONSTRAINT FK_SNS_UP_NO FOREIGN KEY(SNS_NO)
        REFERENCES T_SNS1(SNS_NO)
);

INSERT INTO T_SNS1
VALUES(1, '페북');

INSERT INTO T_SNS_DETAIL1
VALUES (1, 3000);

INSERT INTO T_SNS_UPLOADED1
VALUES(1, 4);

SELECT * FROM
    T_SNS1;

SELECT * FROM
    T_SNS_DETAIL1;
    
SELECT * FROM
    T_SNS_UPLOADED1;