--1) STUDENT 테이블을 참조하여 ST_TEMP 테이블을 만들고 모든 학생의 성적을 4.5만점 기준으로 수정하세요
CREATE TABLE ST_TEMP AS SELECT * FROM STUDENT;
COMMIT;

UPDATE ST_TEMP
	SET 
		AVR = AVR * 1.125;

SELECT *
	FROM ST_TEMP;

--2) PROFESSOR 테이블을 참조하여 PF_TEMP 테이블을 만들고 모든 교수의 부임일자를 100일 앞으로 수정하세요
CREATE TABLE PF_TEMP AS SELECT * FROM PROFESSOR;
COMMIT;

DROP TABLE PF_TEMP;

UPDATE PF_TEMP
	SET
		HIREDATE = HIREDATE - 100;
	
SELECT *
	FROM PF_TEMP;

--3) ST_TEMP 테이블에서 화학과 2학년 학생의 정보를 삭제하세요
DELETE FROM ST_TEMP 
	WHERE ST_TEMP.MAJOR LIKE '%화학%' AND ST_TEMP.SYEAR = 2;
COMMIT;

SELECT *
	FROM ST_TEMP;

--4) PF_TEMP 테이블에서 조교수의 정보를 삭제하세요
DELETE FROM PF_TEMP
	WHERE PF_TEMP.ORDERS LIKE '조교수';
COMMIT;

SELECT *
	FROM PF_TEMP;

--5) EMP 테이블을 참조하여 EMP2 테이블을 만들고 DNO = 30인 사원의 보너스를 15프로 상승시킨 값으로 변경하시고 
--   DNO = 20인 사원의 급여를 10프로 상승시킨 값으로 변경하세요.
CREATE TABLE EMP2 AS SELECT * FROM EMP;
COMMIT;

DROP TABLE EMP2;

UPDATE EMP2
	SET 
		COMM = DECODE(DNO, '30', COMM*1.15, '20', COMM*1.05);

UPDATE EMP2
	SET 
		SAL = SAL * 1.1
	WHERE DNO = 20;

SELECT *
	FROM EMP2;

SELECT *
	FROM EMP;

--6) 화학과 2학년 학생중 기말고사 성적의 등급이 A, B인 정보를 갖는 테이블 SCORE_STGR을 생성하세요.(SNO, SNAME, MAJOR, CNO, CNAME, SYEAR, RESULT, GRADE)
DROP TABLE SCORE_STGR;

CREATE TABLE SCORE_STGR(SNO, SNAME, MAJOR, CNO, CNAME, SYEAR, RESULT, GRADE)
	AS SELECT S.SNO
			, S.SNAME
			, S.MAJOR
			, C.CNO
			, C.CNAME
			, S.SYEAR
			, A.RESULT
			, A.GRADE
		FROM (
				SELECT SC.RESULT
					 , SC.SNO
					 , SC.CNO
	 				 , SG.GRADE
					FROM SCORE SC
					JOIN SCGRADE SG
	  				  ON SC.RESULT BETWEEN SG.LOSCORE AND SG.HISCORE
	  	)A
		JOIN STUDENT S
		  ON S.SNO = A.SNO
		JOIN COURSE C
		  ON C.CNO = A.CNO
		WHERE A.GRADE IN ('A', 'B') AND S.SYEAR = 2 AND S.MAJOR LIKE '%화학%';
	
COMMIT;

SELECT *
FROM SCORE_STGR;
--7) 생물학과 학생중 평점이 2.7이상인 학생이 수강중인 과목의 정보를 갖는 테이블 ST_COURSEPF를 생성하세요. (SNO, SNAME, CNO, CNAME, PNO, PNAME, AVR)
CREATE TABLE ST_COURSEPF(SNO, SNAME, CNO, CNAME, PNO, PNAME, AVR)
	AS SELECT S.SNO
	 , S.SNAME
	 , C.CNO
	 , C.CNAME
	 , P.PNO
	 , P.PNAME
	 , S.AVR
	FROM COURSE C
	JOIN PROFESSOR P
	  ON C.PNO = P.PNO
	JOIN SCORE SC
	  ON C.CNO = SC.CNO 
	JOIN STUDENT S
	  ON SC.SNO = S.SNO 
	WHERE S.AVR >= 2.7 AND S.MAJOR LIKE '생물';
	
