--1) 송강 교수가 강의하는 과목을 검색한다
SELECT C.CNAME
	FROM COURSE C
	JOIN PROFESSOR P
	  ON C.PNO = P.PNO
	WHERE PNAME LIKE '송강';

--2) 화학 관련 과목을 강의하는 교수의 명단을 검색한다
SELECT P.PNAME
	FROM PROFESSOR P
	JOIN COURSE C
	  ON C.PNO = P.PNO
	WHERE CNAME LIKE '%화학%';

--3) 학점이 2학점인 과목과 이를 강의하는 교수를 검색한다
SELECT P.PNAME
	 , C.CNAME
	FROM PROFESSOR P
	JOIN COURSE C
	  ON C.PNO = P.PNO
	WHERE ST_NUM = 2;

--4) 화학과 교수가 강의하는 과목을 검색한다
SELECT C.CNAME
	FROM COURSE C
	JOIN PROFESSOR P
	  ON C.PNO = P.PNO
	WHERE P.SECTION LIKE '화학';

--5) 화학과 1학년 학생의 기말고사 성적을 검색한다
SELECT SC.RESULT
	FROM SCORE SC
	JOIN STUDENT ST 
	  ON ST.SNO = SC.SNO
	WHERE ST.MAJOR LIKE '화학'
	AND ST.SYEAR = 1;

--6) 일반화학 과목의 기말고사 점수를 검색한다
SELECT SC.RESULT
	FROM SCORE SC
	JOIN COURSE C
	  ON C.CNO = SC.CNO
	WHERE C.CNAME LIKE '일반화학';

--7) 화학과 1학년 학생의 일반화학 기말고사 점수를 검색한다
SELECT SC.RESULT
	FROM SCORE SC
	JOIN COURSE C
	  ON C.CNO = SC.CNO
	JOIN STUDENT ST
	  ON SC.SNO = ST.SNO
	WHERE C.CNAME LIKE '일반화학'
	AND ST.MAJOR LIKE '화학'
	AND ST.SYEAR = 1;

--8) 화학과 1학년 학생이 수강하는 과목을 검색한다
SELECT C.CNAME
	FROM COURSE C
	JOIN SCORE SC
	  ON C.CNO = SC.CNO
	JOIN STUDENT ST
	  ON ST.SNO = SC.SNO
	WHERE ST.MAJOR LIKE '화학'
	AND ST.SYEAR = 1;

--9) 유기화학 과목의 평가점수가 F인 학생의 명단을 검색한다
SELECT C.CNAME
	 , ST.SNAME
	FROM COURSE C
	JOIN SCORE SC
	  ON C.CNO = SC.CNO 
	JOIN SCGRADE GR
	  ON SC."RESULT" BETWEEN GR.LOSCORE AND GR.HISCORE 
	JOIN STUDENT ST
	  ON SC.SNO = ST.SNO
	WHERE C.CNAME LIKE '유기화학'
	AND GR.GRADE LIKE 'F';

