--1) 다음 구조를 갖는 테이블을 생성하세요.
--PRODUCT 테이블 - PNO NUMBER PK              : 제품번호
--                PNMAE VARCHAR2(50)          : 제품이름
--                PRI NUMBER                  : 제품단가
--PAYMENT 테이블 - MNO NUMBER PK              : 전표번호
--               PDATE DATE NOT NULL         : 판매일자
--                CNAME VARCHAR2(50) NOT NULL : 고객명
--                TOTAL NUMBER TOTAL > 0      : 총액
--PAYMENT_DETAIL - MNO NUMBER PK FK           : 전표번호
--                PNO NUMBER PK FK            : 제품번호
--                AMOUNT NUMBER NOT NULL      : 수량
--                PRICE NUMBER NOT NULL       : 단가
--                TOTAL_PRICE NUMBER NOT NULL TOTAL_PRICE > 0 : 금액

CREATE TABLE PRODUCT(
    PNO NUMBER(4) PRIMARY KEY,
    PNMAE VARCHAR2(50),
    PRI NUMBER(5)
);

CREATE TABLE PAYMENT(
    MNO NUMBER(4) PRIMARY KEY,
    PDATE DATE NOT NULL,
    CNAME VARCHAR2(50) NOT NULL,
    TOTAL NUMBER(4) CHECK(TOTAL > 0) NOT NULL
);

CREATE TABLE PAYMENT_DETAIL(
    MNO NUMBER(4),
    PNO NUMBER(4),
    AMOUNT NUMBER(4) NOT NULL,
    PRICE NUMBER(4) NOT NULL,
    TOTAL_PRICE NUMBER(5) CHECK(TOTAL_PRICE>0) NOT NULL,
    CONSTRAINT PAYMENT_DETAIL_MNO_FK FOREIGN KEY(MNO) REFERENCES PAYMENT(MNO),
    CONSTRAINT PAYMENT_DETAIL_PNO_FK FOREIGN KEY(PNO) REFERENCES PRODUCT(PNO)
);