--1) SCORE 테이블과 동일한 구조를 갖는 SCORE_CHK를 생성하고 RESULT 60이상 90이하만 입력 가능하도록 하세요.
CREATE TABLE SCORE_CHK(
 		  SNO VARCHAR2(8),
		  CNO VARCHAR2(8),
		  RESULT NUMBER(3, 0),
		  CONSTRAINT CHK_SCORE_CHK_RESULT CHECK(RESULT BETWEEN 60 AND 90)
		);
	
--2) STUDENT 테이블과 동일한 구조를 갖는 STUDENT_COPY 테이블을 생성하면서 
-- 	 SNO은 PK로 SNAME은 NOT NULL로 SYEAR의 DEFAULT는 1로 
--   설정하세요.
CREATE TABLE STUDENT_COPY (
	SNO VARCHAR2(8) PRIMARY KEY,
	SNAME VARCHAR2(20) NOT NULL,
	SEX VARCHAR2(3),
	SYEAR NUMBER(1,0) DEFAULT 1,
	MAJOR VARCHAR2(20),
	AVR NUMBER(4,2)
);

--3) COURSE 테이블과 동일한 구조를 갖는 COURSE_CONTSRAINT 테이블을 생성하면서 
-- 	 CNO, CNAME을 PK로 PNO은 PROFESSOR_PK의 PNO을 참조하여
--   FK로 설정하고 ST_NUM은 DEFAULT 2로 설정하세요.
CREATE TABLE PROFESSOR_PK
AS SELECT * FROM PROFESSOR;

ALTER TABLE PROFESSOR_PK 
ADD CONSTRAINT PK_PROFESSOR_PK_PNO PRIMARY KEY(PNO);

DROP TABLE PROFESSOR_PK;

CREATE TABLE COURSE_CONTSRAINT (
	CNO VARCHAR2(8),
	CNAME VARCHAR2(20),
	ST_NUM NUMBER(1,0),
	PNO VARCHAR2(8),
	CONSTRAINT PK_COURSE_CONTSRAINT_CNO_CNAME PRIMARY KEY (CNO, CNAME),
	CONSTRAINT FK_COURSE_CONTSRAINT_PNO FOREIGN KEY(PNO)
	REFERENCES PROFESSOR_PK(PNO)
);












